language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache: cargo

addons:
  apt:
    packages:
      - libvulkan-dev

install:
  - cargo build --verbose --features vulkan

script:
  - cargo build --verbose --features vulkan
  - cargo test --verbose --features vulkan