language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache: cargo

install:
  - cargo build --verbose --features empty

script:
  - cargo build --verbose --features empty
  - cargo test --verbose --features empty