[package]
name = "polystrip"
description = "A 2D accelerated graphics rendering library"
keywords = ["gamedev", "graphics", "rendering"]
categories = ["game-development", "graphics", "rendering::engine"]
version = "0.6.0"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
repository = "https://github.com/TheOnlyMrCat/polystrip"
license = "MIT OR Apache-2.0"
edition = "2021"

[package.metadata.docs.rs]
features = ["glyph_brush"]

[features]
default = ["gon"]
gon = []
tui = []

[dependencies]
wgpu.version = "0.12"
wgpu.features = ["spirv"]

bytemuck = "1.5"
mint = "0.5"
raw-window-handle = "0.4"
arrayvec = "0.5"

glyph_brush = { version = "0.7", optional = true }

[dev-dependencies]
winit = "0.26"
winit_input_helper = "0.10.0"
image = "0.23"
pollster = "0.2"

[[example]]
name = "text"
required-features = ["gon", "glyph_brush"]