[package]
name = "polystrip"
description = "A 2D accelerated graphics rendering library"
keywords = ["gamedev", "graphics", "rendering"]
categories = ["game-development", "graphics", "rendering::engine"]
version = "0.7.0"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
repository = "https://github.com/TheOnlyMrCat/polystrip"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["gon"]
gon = []
tui = []
serde_math = ["serde", "mint/serde"]

[dependencies]
wgpu = "0.13.1"

bytemuck = "1.10.0"
mint = "0.5.9"
raw-window-handle = "0.4.3"

serde = { version = "1.0.138", features = ["derive"], optional = true }
indexmap = "1.9.1"
wgpu-types = "0.13.0"
either = "1.7.0"
fxhash = "0.2.1"

[dev-dependencies]
winit = "0.26.1"
winit_input_helper = "0.12.0"
image = "0.24.2"
pollster = "0.2.5"
time = { version = "0.3.7", features = ["local-offset"] }
bytemuck = { version = "1.10.0", features = ["derive"] }
libc = "0.2.126"
