[package]
name = "polystrip"
description = "A 2D accelerated graphics rendering library"
keywords = ["gamedev", "graphics", "rendering"]
categories = ["game-development", "graphics", "rendering::engine"]
version = "0.3.1"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
repository = "https://github.com/TheOnlyMrCat/polystrip"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
wgpu = "0.6"
bytemuck = "1.4"
futures = "0.3"
raw-window-handle = "0.3"

[dev-dependencies]
winit = "0.23"
image = "0.23"