[package]
name = "polystrip"
description = "A 2D accelerated graphics rendering library"
keywords = ["gamedev", "graphics", "rendering"]
categories = ["game-development", "graphics", "rendering::engine"]
version = "0.4.0"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
repository = "https://github.com/TheOnlyMrCat/polystrip"
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
vulkan = ["gfx-backend-vulkan"]
metal = ["gfx-backend-metal"]
dx12 = ["gfx-backend-dx12"]

[dependencies]
bytemuck = "1.4"
raw-window-handle = "0.3"
align-data = "0.1"
gpu-alloc = "0.2"
gpu-alloc-gfx = "0.1"

gfx-hal = "0.6"
gfx-backend-vulkan = { version = "0.6", optional = true }
gfx-backend-metal = { version = "0.6", optional = true }
gfx-backend-dx12 = { version = "0.6", optional = true }

[dev-dependencies]
winit = "0.23"
image = "0.23"
